//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmegaLabsZero.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAQ_PERGUNTAS
    {
        public int FAQ_ID { get; set; }
        public string FAQ_TITULO { get; set; }
        public string FAQ_PERGUNTA { get; set; }
        public string FAQ_RESPOSTA { get; set; }
        public int STA_ID { get; set; }
    
        public virtual STA_STATUS STA_STATUS { get; set; }
    }
}
