//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmegaLabsZero.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOT_NOTICIA
    {
        public int NOT_ID { get; set; }
        public string NOT_TITULO { get; set; }
        public string NOT_PREVIA { get; set; }
        public string NOT_TEXTO { get; set; }
        public System.DateTime NOT_INCLUSAO { get; set; }
        public Nullable<System.DateTime> NOT_ALTERACAO { get; set; }
        public Nullable<System.DateTime> NOT_PUBICACAO { get; set; }
        public int STA_ID { get; set; }
    
        public virtual STA_STATUS STA_STATUS { get; set; }
    }
}
