//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmegaLabsZero.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OmegaModelContainer : DbContext
    {
        public OmegaModelContainer()
            : base("name=OmegaModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CID_CIDADE> CID_CIDADE { get; set; }
        public virtual DbSet<CON_CONCURSO> CON_CONCURSO { get; set; }
        public virtual DbSet<EST_ESTADO> EST_ESTADO { get; set; }
        public virtual DbSet<FAQ_PERGUNTAS> FAQ_PERGUNTAS { get; set; }
        public virtual DbSet<NOT_NOTICIA> NOT_NOTICIA { get; set; }
        public virtual DbSet<STA_STATUS> STA_STATUS { get; set; }
        public virtual DbSet<SUB_SUBSTANCIA> SUB_SUBSTANCIA { get; set; }
        public virtual DbSet<USR_USUARIO> USR_USUARIO { get; set; }
    }
}
