//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmegaLabsZero.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STA_STATUS
    {
        public STA_STATUS()
        {
            this.CON_CONCURSO = new HashSet<CON_CONCURSO>();
            this.FAQ_PERGUNTAS = new HashSet<FAQ_PERGUNTAS>();
            this.NOT_NOTICIA = new HashSet<NOT_NOTICIA>();
            this.SUB_SUBSTANCIA = new HashSet<SUB_SUBSTANCIA>();
            this.USR_USUARIO = new HashSet<USR_USUARIO>();
        }
    
        public int STA_ID { get; set; }
        public string STA_NOME { get; set; }
    
        public virtual ICollection<CON_CONCURSO> CON_CONCURSO { get; set; }
        public virtual ICollection<FAQ_PERGUNTAS> FAQ_PERGUNTAS { get; set; }
        public virtual ICollection<NOT_NOTICIA> NOT_NOTICIA { get; set; }
        public virtual ICollection<SUB_SUBSTANCIA> SUB_SUBSTANCIA { get; set; }
        public virtual ICollection<USR_USUARIO> USR_USUARIO { get; set; }
    }
}
