//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmegaLabsZero.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USR_USUARIO
    {
        public int USR_ID { get; set; }
        public string USR_NOME { get; set; }
        public string USR_EMAIL { get; set; }
        public string USR_SENHA { get; set; }
        public int STA_ID { get; set; }
    
        public virtual STA_STATUS STA_STATUS { get; set; }
    }
}
